<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'akilesh@berkeley.edu',
		'to' => 'akilesh@berkeley.edu'
	),
	'fields' => array(
		'Email' => array(
			'order' => 1,
			'type' => 'email',
			'label' => 'Invention Name',
			'required' => false,
			'errors' => array(
				'format' => 'Field \'Invention Name\' has an invalid email.'
			)
		),
		'custom_U303' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Message',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U435' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Message',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U840' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Custom',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U868' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Custom',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U692' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'Checkbox Group',
			'required' => true,
			'optionItems' => array(
				'Invention in Progress',
				'Invention in Ideation'
			),
			'errors' => array(
				'required' => 'Field \'Checkbox Group\' is required.',
				'format' => 'Field \'Checkbox Group\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
